apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-files
  namespace: wordpress
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 1Gi
