{service.type: ClusterIP, persistence.accessModes: ReadWriteMany, persistence.storageClass: aws-efs, persistence.size: 10Gi, persistence.existingClaim: wp-files, pdb.create: true, pdb.minAvailable: 3}
